### ISSUE TITLE
_pagefind/pagefind.js 404

### ISSUE THREAD

**Issue by Qiu-Jun** [ATQQ/sugar-blog#101]
**@sugarat/theme版本 0.1.30**

在html中有这个动态导入代码 
```javascript
import('/_pagefind/pagefind.js')
  .then((module) => {
    window.__pagefind__ = module
  })
  .catch(() => {
    console.log('not load /_pagefind/pagefind.js')
  })
```

**Comment by ATQQ** [comment]
嗯，这个提示只会在dev的时候有

因为 /_pagefind/pagefind.js 这个文件只在 build 还才会生成

**Comment by ATQQ** [comment]
插入这段代码的逻辑是 使用 使用主题内置的搜索 pagefind，详见文档说明 [@sugarat/theme - 全文搜索](https://theme.sugarat.top/config/global.html#%E5%85%A8%E6%96%87%E6%90%9C%E7%B4%A2-pagefind)

**Comment by Qiu-Jun** [comment]
> 插入这段代码的逻辑是 使用 使用主题内置的搜索 pagefind，详见文档说明 [@sugarat/theme - 全文搜索](https://theme.sugarat.top/config/global.html#%E5%85%A8%E6%96%87%E6%90%9C%E7%B4%A2-pagefind)

Ok
