### ISSUE TITLE
标题栏如何配置？

### ISSUE THREAD

**Issue by gaohc001** [ATQQ/sugar-blog#104]
我在docs/.vitepress/config.ts的const blogTheme = getThemeConfig({nav:[{text:'home',link:'/'}]....
不起作用呢

**Comment by ATQQ** [comment]
那个在 Vitepress 的配置里设置，这个`getThemeConfig ` 只配置主题独有的配置详见文档

https://theme.sugarat.top/config/global.html

```ts
import { getThemeConfig, defineConfig } from '@sugarat/theme/node'

const blogTheme = getThemeConfig()

export default defineConfig({
  extends: blogTheme,
  // ...other config
  // vitepress 默认主题配置↓
  themeConfig:{
   nav:[]
  }
})
```

主题继承[默认主题配置](https://vitepress.dev/reference/site-config)，即原主题配置依然生效

官方内置的👉🏻 [markdown 能力](https://vitepress.vuejs.org/guide/markdown) 👈🏻
