### ISSUE TITLE
大佬的博客为啥没有用自己做的本地搜索插件。

### ISSUE THREAD

**Issue by xxxxue** [ATQQ/sugar-blog#122]
https://github.com/ATQQ/sugar-blog/blob/74814ed44a3ffe0576daa5476b2b24fdf16d32dc/packages/blogpress/.vitepress/config.ts#L142C8-L142C8

**Comment by ATQQ** [comment]
使用在线的搜索效果目前是比离线的要强一点

现在主流的文档站搜索大部分也是用的Algolia

在线搜索接入需要有个申请的流程，需要手动或定时触发爬虫服务更新

这个也看取舍，无网络要求或者不希望被爬取的内容一般才用离线的搜索

**Comment by ATQQ** [comment]
remind
