### ISSUE TITLE
mac打包失败

### ISSUE THREAD

**Issue by Qiu-Jun** [ATQQ/sugar-blog#125]
Binary failed to download — package expected to have downloaded the binary to /Users/june/Desktop/my_blog/node_modules/.pnpm/pagefind@0.12.0/node_modules/pagefind/bin/pagefind_extended during its postinstall
Do you have install scripts disabled for npm?
Try running `npm config set ignore-scripts false` and re-installing.
Otherwise, your platform might not be supported. Open an issue on GitHub!
build error:

pagefind 不支持mac吗

**Comment by Qiu-Jun** [comment]
我在win打包是正常的。换mac后会卡在pagefind下载，然后我手动安装了，还是报错

**Comment by ATQQ** [comment]
不应该啊，可能是包有些问题 你可以pagefind的仓库看一下



是有说win上 有问题的，没说mac有问题😂

你用的什么镜像源 淘宝的吗

**Comment by Qiu-Jun** [comment]
> 不应该啊，可能是包有些问题 你可以pagefind的仓库看一下
> 
> 
> 
> 是有说win上 有问题的，没说mac有问题😂
> 
> 你用的什么镜像源 淘宝的吗

淘宝，我有空再看看
