### ISSUE TITLE
如何被搜索引擎收录网址

### ISSUE THREAD

**Issue by lpdswing** [ATQQ/sugar-blog#128]
比如百度的标签验证，应该如何做呢

**Comment by ATQQ** [comment]
哈哈😁，刚看到，百度的SEO 我也不是很清楚咋搞 不过只是收录域名应该不麻烦

**Comment by lpdswing** [comment]
> 哈哈😁，刚看到，百度的SEO 我也不是很清楚咋搞 不过只是收录域名应该不麻烦
已经搞定，https://github.com/mqyqingfeng/Blog/issues/272
