### ISSUE TITLE
bug: 当文章页面位置在最顶部时，右侧大纲会在最后一个标题激活

### ISSUE THREAD

**Issue by rennzhang** [ATQQ/sugar-blog#138]
查看了vitepress文档木有这个问题，看了下源码，但是没有头绪

此时处于页面最上方，效果如下：
![image](https://github.com/ATQQ/sugar-blog/assets/50518861/5f0a20b1-5707-4145-ab8e-3b9eb9c8cda1)

**Comment by ATQQ** [comment]
Get 之前也发现了 没注意😂 我也以为vitepress bug嘞 我明后天看看 可能是我hack了什么东西导致的

**Comment by ATQQ** [comment]
> 👍 大佬知道大概在哪里解决的话我可以帮忙解决一下

没问题，我周末看一下，周中确实太忙了，顾不上

**Comment by ATQQ** [comment]
看了一下 VitePress 源码 大概是下面这段代码 @rennzhang 

https://github.com/vuejs/vitepress/blob/0d56855b54a97d4350485ee76c07a040fdc5738c/src/client/theme-default/composables/outline.ts#L145-L151
```ts
const isBottom = Math.abs(scrollY + innerHeight - offsetHeight) < 1

    // page bottom - highlight last one
    if (anchors.length && isBottom) {
      activateLink(anchors[anchors.length - 1].hash)
      return
    }
```

在我这个主题上 isBottom 判断出现了问题，具体是哪块影响的我再进一步看一下

**Comment by ATQQ** [comment]
这个是 vitepress 正常初识的值(我这个设备)
```txt
scrollY 0
innerHeight 1067
offsetHeight 3129
abs 2062
```

主题上异常的值
```txt
scrollY 0
innerHeight 1067
offsetHeight 1067
abs 0
```

大概就是`window.innerHeight` 和`document.body.offsetHeight` 一样了导致的这个问题(在我这个主题上)，应该是我这边的样式影响了 body 的 offsetHeight 高度

**Comment by ATQQ** [comment]
这个bug在主题里是  [vitepress-plugin-pagefind](https://www.npmjs.com/package/vitepress-plugin-pagefind) 这个插件引入的 我先迭代一下我这边

你可以尝试在 vitepress 侧优化一下那个 isBottom 的判断，兼容这个case
```css
html,
body{
  height: 100%;
}
```

**Comment by ATQQ** [comment]
修复代码见

https://github.com/ATQQ/sugar-blog/pull/140/files#diff-624ff9b1e80bac80e7f7235ab1169dde84f9965a542b1891c49ad350e622f7a4
