### ISSUE TITLE
更新主题后，分页样式颜色被覆盖导致显示错误

### ISSUE THREAD

**Issue by Qiu-Jun** [ATQQ/sugar-blog#146]
![image](https://github.com/ATQQ/sugar-blog/assets/24954362/f94f8030-82e1-4465-bc99-4a7d73ce9eef)

**Comment by Qiu-Jun** [comment]
如图，更新了0.2.6版本后，样式被覆盖

**Comment by Qiu-Jun** [comment]
![image](https://github.com/ATQQ/sugar-blog/assets/24954362/6fca5fd4-401f-4030-85f1-09f49ba21c28)


config.ts配置了base会导致右侧个人信息的头像加载失败，左上角正常

**Comment by ATQQ** [comment]
Get ，今天晚点我看看修复一下，感谢反馈

@Qiu-Jun

**Comment by ATQQ** [comment]
base 的问题在 最新的 0.2.7 修复了，可以更新一下依赖

那个样式被覆盖的问题，我这没有复现，你可以先看一下[主题色 的文档  ](https://theme.sugarat.top/config/style.html#%E4%B8%BB%E9%A2%98%E8%89%B2)，如果无法解决你的问题，可以来个复现的demo发我一下 

@Qiu-Jun

**Comment by Qiu-Jun** [comment]
> base 的问题在 最新的 0.2.7 修复了，可以更新一下依赖
> 
> 那个样式被覆盖的问题，我这没有复现，你可以先看一下[主题色 的文档 ](https://theme.sugarat.top/config/style.html#%E4%B8%BB%E9%A2%98%E8%89%B2)，如果无法解决你的问题，可以来个复现的demo发我一下
> 
> @Qiu-Jun

我大概知道了，上面那个样式的图var(--vp-c-brand-2)这个变量没有值导致的，我把这个变量在自定义样式里赋值就可以了
`:root {
  --vp-c-brand-2: var(--el-color-primary);
}`

现在可以了。感谢
