### ISSUE TITLE
rss plugin: frontmatter.publish 更多解释？

### ISSUE THREAD

**Issue by shiny** [ATQQ/sugar-blog#150]
我想找一个控制文章是否输出到 RSS 的选项，看到 frontmatter.publish 很适合。

Q：是否只影响 rss plugin 生成逻辑，不影响 vitepress 其他部分？比如 sitemap 中还是包含了 publish = false 的文章

**Comment by ATQQ** [comment]
这块 文档里确实漏了目前RSS插件行为里确实会过滤 publish:  false 的文章

代码见这里，回头补一下文档

https://github.com/ATQQ/sugar-blog/blob/6b1f44210e63752dc0e708817ff5c5e56a9383a5/packages/vitepress-plugin-rss/src/node.ts#L114C9-L114C9

这个属性是自定义的具体会不会影响其它的，目前看Vitepress 文档里并没有拓展这个

sitemap 的话这个可能得看一下[VitePress这部分的文档](https://vitepress.dev/guide/sitemap-generation#options)了（当然只是想看是否生效，最快的方式可以用demo 跑一跑）

**Comment by ATQQ** [comment]
🥔 晚点再细看一下 VitePress 内置的sitemap 逻辑

**Comment by shiny** [comment]
感谢解答 🙏
因为有部分页面（例如友情链接页面）不想输出到 rss，但是可以输出到 sitemap。
已经用上这个插件了，效果很好。

**Comment by ATQQ** [comment]
这部分内容补充好了，然后额外添加了一个 filter 方法 可以用于自定义逻辑的过滤

https://github.com/ATQQ/sugar-blog/tree/master/packages/vitepress-plugin-rss

```ts
const RSS: RSSOptions = {
  // 省略其它参数
  filter: (post, idx, array) => {
    return true
  }
}

```
