### ISSUE TITLE
文章frontMatter使用本地cover，部署后在index页面图片路径错误

### ISSUE THREAD

**Issue by Ymriri** [ATQQ/sugar-blog#157]
<img width="530" alt="image" src="https://github.com/ATQQ/sugar-blog/assets/56512874/c415a9bd-a34e-43ea-8f62-d59a1870b455">

1. 使用默认cover，自动提取第一张作为封面图，博客内图片地址是`/images/f1ce52f08ad9864f3bc30d2c2f9b7336.jpeg`
2. 文章的图片地址**build**后会变成`/assets/f1ce52f08ad9864f3bc30d2c2f9b7336.dO6K0w_d.jpeg`，但index封面图还是`/images/f1ce52f08ad9864f3bc30d2c2f9b7336.jpeg` 
---
不确定vitepress编译后的静态文件目录是否都在`assets`，如果是的话修复就比较简单，直接判断是否是项目静态文件，如果是的话直接把路径强行变成`/assets/xxx`。
不确定是否有其他影响，有什么其他配置可以更优雅的解决这个问题更好~

**Comment by ATQQ** [comment]
这个问题已修复啦 详见 commit：https://github.com/ATQQ/sugar-blog/commit/9b3c41d3117c6581b48db7d5bf5019a1ccb5d791#diff-2792f741579b1f2c72f7c5b782e959e570b1a3580c038d83fc59a398cbf99e2f


但如果是手动在 frontmatter 指定相对路径的图片的化 目前仍然不会生效，这个计划后面在修复（待设计一个通用的插件处理 frontMatter中的图片）

**Comment by ATQQ** [comment]
目前兼容了 手动指定cover 详见 commit https://github.com/ATQQ/sugar-blog/commit/9256732f6499c94f4f1c8f847d89fe6fd7746862

使用非 public 的相对路径文件
```md
---
cover: /sop/test/a/image.png
---
# 测试相对路径 Cover

<img src="./image.png" style="display:none;"/>

正常内容内容
```
目录结构
```sh
├── README.md
├── docs
|  ├── about.md
|  ├── index.md
|  ├── public
|  |  ├── favicon.ico
|  |  ├── logo.png
|  |  └── robots.txt
|  └── sop
|     ├── component.md
|     ├── more.md
|     ├── quickStart.md
|     ├── style.md
|     └── test
|        └── a
|           ├── bcf.md
|           └── image.png

directory: 5 file: 14
```

构建后预览
<img width="870" alt="image" src="https://github.com/ATQQ/sugar-blog/assets/42485491/0ecdf585-3d24-4182-bba2-c4c1fe4b6f1a">
