### ISSUE TITLE
index.md问题

### ISSUE THREAD

**Issue by myzf** [ATQQ/sugar-blog#163]
还记得index.md，vitepress不能显示这个markdown，最后你怎么解决了

**Comment by myzf** [comment]
我用homecontent包了一层，里面写markdown还是不生效

**Comment by ATQQ** [comment]
> 还记得index.md，vitepress不能显示这个markdown，最后你怎么解决了

我直接没在首页写了 markdown了害。

如果写的你可以看看之前那个issue 好像有提 解决方案

现在我能想到的是 它应该是提供了markdown解析的 只是 layout:home 场景下 不会有样式注入 你可以看一下 layout组件 把它的样式import一下应该也行

**Comment by myzf** [comment]
我对ts这个不大熟悉，觉得他这个有点蠢，vuepress都支持，它就不行，描述的意思我知道大概就是避免样式冲突。你有空没，能帮我看看怎么改不，看了那个index.js也没找到咋设置吧

**Comment by myzf** [comment]
好滴不管咋样，先谢谢啦

**Comment by ATQQ** [comment]
@myzf 搞定

你参考这个 commit 改一下就行引入个局部的样式

https://github.com/ATQQ/sugar-blog/commit/1ae39e2b1fe8d1ec2040f1986ca30b693c9640f3

---
效果你可以看我主题 首页 https://theme.sugarat.top/#%E2%9A%A1-%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B

![image](https://github.com/ATQQ/sugar-blog/assets/42485491/3cc452e2-da90-4a28-90fb-523c8655aa21)

**Comment by myzf** [comment]
> @myzf 搞定
> 
> 你参考这个 commit 改一下就行引入个局部的样式
> 
> [1ae39e2](https://github.com/ATQQ/sugar-blog/commit/1ae39e2b1fe8d1ec2040f1986ca30b693c9640f3)
> 
> 效果你可以看我主题 首页 https://theme.sugarat.top/#%E2%9A%A1-%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B
> 
> ![image](https://private-user-images.githubusercontent.com/42485491/294517652-3cc452e2-da90-4a28-90fb-523c8655aa21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MzQ1MTYsIm5iZiI6MTcwNDUzNDIxNiwicGF0aCI6Ii80MjQ4NTQ5MS8yOTQ1MTc2NTItM2NjNDUyZTItZGE5MC00YTI4LTkwZmItNTIzYzg2NTVhYTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDA5NDMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjYjI1YmY1MWZhZDVjOWQ5N2QzN2EwMDJlYjU1MWJhNmZkZWJmYzAzNGM0ODM4NzdhYmEyMDczNTA0ZjFjNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M08IfE6_IeQyI64mrG2fErok1uQvASHMqB0OAafC8s4)

收到了试了试是ok的，多谢多谢哈
