### ISSUE TITLE
Mermaid流程图打包问题

### ISSUE THREAD

**Issue by ZerxZ** [ATQQ/sugar-blog#169]
Mermaid流程图
pnpm dev 开发环境下运行博客显示没有问题
如果开始pnpm build 打包 显示不出来问题不知道什么原因造成?
![image](https://github.com/ATQQ/sugar-blog/assets/71170059/e5be8d1c-05b1-418f-81fa-b5c9c4ce7238)

博客仓库:
https://github.com/ZerxZ/zerxz-blog
博客网站链接:
https://zerxzonline.com/godot/godot_execution_order.html

**Comment by ATQQ** [comment]
收到，已知问题，没来得及修。

之前升级vitepress后出现的(可能是Vite从4到5后出现的)


今天我优先跟进一下
