### ISSUE TITLE
[feat] vitepress-plugin-pagefind 可否增加类似 minisearch 的搜索预览

### ISSUE THREAD

**Issue by shellRaining** [ATQQ/sugar-blog#182]
如题，在使用 vitepress 内置的 minisearch 的时候会出现预览的选项，可否增加该功能

**Comment by ATQQ** [comment]
你可以来个截图我看看具体啥效果，然后我下来pagefind能否有相关API给予支持。

**Comment by shellRaining** [comment]
<img width="885" alt="image" src="https://github.com/ATQQ/sugar-blog/assets/111564053/d8b71dcf-44b0-4bc9-855e-2d5f97958409">

类似图中效果，能够显示出在文章中的位置

**Comment by ATQQ** [comment]
好的 我下来抽时间看一下能否实现

**Comment by ATQQ** [comment]
这个效果的预览模式可能不太好做，现在确实累计了一些问题 预计本周会优化一下，增强一下体验，敬请期待。
