### ISSUE TITLE
若干个问题

### ISSUE THREAD

**Issue by 1gcat** [ATQQ/sugar-blog#193]
以下方案可能是治标不治本的，我前端太菜了，还请作者有空时看看怎么解决。

## 环境
- OS：Windows 11 23H2 22631.3296 X64
- Node：v20.10.0 X64
- IDE：VSCode

## pnpm install

报错：![1](https://github.com/ATQQ/sugar-blog/assets/43435652/f65ec5f0-968b-4032-897f-28f01096909a)

删除 `packages/theme/package.json` 下的 
```json
"pnpm": {
    "peerDependencyRules": {
      "ignoreMissing": [
        "@algolia/client-search",
        "search-insights"
      ]
    }
  }
```
解决

## pnpm dev

如果使用 `pnpm --filter 'blogpress' dev`

报错：No projects matched the filters...

改为 `pnpm -r --filter=./packages/blogpress dev` 解决

## pnpm buildlib
如果使用 `pnpm run '/^build:.*/'` 

报错：![0](https://github.com/ATQQ/sugar-blog/assets/43435652/e3d9cdc2-14a4-4916-977c-070666b199e6)

改为 `pnpm run \"/^build:.*/\"`  
报错：No projects matched the filters...

改为 `pnpm -r --filter=./packages/** build` 解决

但是有很多这种警告，虽然不影响启动，但感觉还是要解决的：
![4](https://github.com/ATQQ/sugar-blog/assets/43435652/d04ded80-f38d-4da8-9863-6825b6a3e425)
![5](https://github.com/ATQQ/sugar-blog/assets/43435652/353121eb-5732-41f2-b39b-794901a839f5)
![6](https://github.com/ATQQ/sugar-blog/assets/43435652/c08a47a9-b983-4fb7-86bc-6f24462d5714)

## 启动后

控制台警告：[Vue warn]: Component "Mermaid" has already been registered in target app.

`packages/theme/src/index.ts`
注册前先判断是否已经注册过

```TypeScript
    if (!ctx.app.component('Mermaid')) {
      ctx.app.component('Mermaid', Mermaid as any)
    }
```

**Comment by ATQQ** [comment]
可以的 你可以来个PR，我晚点验证一下 Mac上也能用的话 就直接用这个

**Comment by ATQQ** [comment]
都搞定啦

具体改动你可以看关联的几个commit，和你给到的方法有一些出入
