### ISSUE TITLE
首页精选文章跳转错误的问题

### ISSUE THREAD

**Issue by i-mufeng** [ATQQ/sugar-blog#194]
在没有配置丢掉 .html 的情况下，点击首页精选文章跳转，页面会错误显示，加上 .html  显示正常。
示例：
![recording](https://github.com/ATQQ/sugar-blog/assets/68867110/0a2dfc18-7bc3-4aab-a9fc-230deae12857)

**Comment by ATQQ** [comment]
可参考 这个配置解决

https://theme.sugarat.top/config/inline-matter.html#cleanurls

默认生成的菜单路由按照 cleansUrl 处理的没带后缀，我先记个优化后面处理

**Comment by ATQQ** [comment]
下一版发版带上，已做兼容
