### ISSUE TITLE
更新0.2.30，mac打包内存溢出

### ISSUE THREAD

**Issue by Qiu-Jun** [ATQQ/sugar-blog#196]
<img width="1064" alt="image" src="https://github.com/ATQQ/sugar-blog/assets/24954362/3a9647f3-ee87-45ad-a65d-603429a75a71">

**Comment by ATQQ** [comment]
你尝试回退一下 这个依赖得版本

https://theme.sugarat.top/config/component.html#oml2d-%E7%9C%8B%E6%9D%BF%E5%A8%98%E9%9B%86%E6%88%90

0.13.0

**Comment by ATQQ** [comment]
你得 vitepress 版本好像不对也。你要不 升级一下 `1.0.1`

![image](https://github.com/ATQQ/sugar-blog/assets/42485491/9e3f469d-3fbc-4468-9e45-af34d8dc2995)

**Comment by ATQQ** [comment]
你先把 VitePress 版本调正确再试一下吧

**Comment by Qiu-Jun** [comment]
> 你得 vitepress 版本好像不对也。你要不 升级一下 `1.0.1`
> 
> 
> 
> ![image](https://github.com/ATQQ/sugar-blog/assets/42485491/9e3f469d-3fbc-4468-9e45-af34d8dc2995)
> 
> 

晚上试试

**Comment by Qiu-Jun** [comment]
> 你先把 VitePress 版本调正确再试一下吧

需要vite1.0.1和vue3.3+。另外问下。大佬要不要把主题仓库和你博客本身分离一下，每次同步只想同步主题仓库

**Comment by ATQQ** [comment]
> > 你先把 VitePress 版本调正确再试一下吧
> 
> 需要vite1.0.1和vue3.3+。另外问下。大佬要不要把主题仓库和你博客本身分离一下，每次同步只想同步主题仓库

你是fork了仓库吗？还是什么情况

**Comment by Qiu-Jun** [comment]
> > > 你先把 VitePress 版本调正确再试一下吧
> 
> > 
> 
> > 需要vite1.0.1和vue3.3+。另外问下。大佬要不要把主题仓库和你博客本身分离一下，每次同步只想同步主题仓库
> 
> 
> 
> 你是fork了仓库吗？还是什么情况

是的，fork了

**Comment by ATQQ** [comment]
不冲突嘛。。

你自己的博客的话就单独开一个仓库就行 不用在我fork的里面改，有需要同步的 github也提供了一键同步。

每个都弄仓库单独维护的话 太散了 调试也没那么方便
