### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by 321paranoiawhy** [ATQQ/sugar-blog#233]
[link](https://github.com/ATQQ/sugar-blog/blob/master/packages/theme/README.md?plain=1#L45)

`## Advanced Ssage` should be `## Advanced Usage`

**Comment by ATQQ** [comment]
Get，方便得话可以来个 PR hh

**Comment by 321paranoiawhy** [comment]
> Get，方便得话可以来个 PR hh

It is too small, hh

You can do it yourself (orz
