### ISSUE TITLE
RSS 文件内容出现乱码问题

### ISSUE THREAD

**Issue by JacindaTang** [ATQQ/sugar-blog#265]
在Vitepress里添加成功之后，点击Rss图标进入，页面出现了乱码问题，想知道该如何解决😭

**Comment by ATQQ** [comment]
RSS 那个文件内容乱码么，自己配一下机器上的Nginx配置，修改一下 response content-type编码。

其次这个编码问题那些RSS软件会自动拿正确编码读取内容吧，应该不用太关心。

**Comment by JacindaTang** [comment]
> RSS 那个文件内容乱码么，自己配一下机器上的Nginx配置，修改一下 response content-type编码。
> 
> 其次这个编码问题那些RSS软件会自动拿正确编码读取内容吧，应该不用太关心。

好的，谢谢！

**Comment by ATQQ** [comment]
https://github.com/ATQQ/sugar-blog/commit/a3b9ad4f9248ceabaf38ef15d6f2e60e7345db83

add docs
