### ISSUE TITLE
请问一下大佬，如何修改底部栏呢？

### ISSUE THREAD

**Issue by admin8800** [ATQQ/sugar-blog#268]
![1](https://github.com/user-attachments/assets/bcfef617-4071-4bb4-95ea-381deaf255f0)

### 请问一下如何修改底部版权的文本呢？当然我不是说要去掉版权链接，只是觉得文本这样写有点不优雅，我觉得可以改成`sugar-blog`或者`theme`字样，当然链接不变，一个小建议 🥰

github工作流部署的

**Comment by ATQQ** [comment]
按照目前配置方式 https://theme.sugarat.top/config/global.html#footer

①  先隐藏掉 `version: false`
② 按照配置自定义一个替换

---
当然也可以把这块做成可配置的，后面我加一下 哈哈

**Comment by ATQQ** [comment]
已支持 https://theme.sugarat.top/config/global.html#footer

<img width="747" alt="image" src="https://github.com/user-attachments/assets/5c735fe1-c6f4-4252-a2c7-4898ed0837a0">
