### ISSUE TITLE
生成的 rss 带有 `&ZeroWidthSpace;`

### ISSUE THREAD

**Issue by shiny** [ATQQ/sugar-blog#276]
我发现自己的博客在 inoreader 上人订阅，看了下内容格式，标题都带了`&ZeroWidthSpace;`
<img width="712" alt="图片" src="https://github.com/user-attachments/assets/53f09460-fa0a-4b04-8366-9f78c9f01b5c">

相关 issue: 
- https://github.com/vuejs/vitepress/issues/3364

请问有什么办法能修复这个问题?
谢谢

**Comment by ATQQ** [comment]
没问题，可以修复，我抽空弄一下，看了一比较简单，你方便的化也可以来PR 哈哈

**Comment by ATQQ** [comment]
参考这个PR：https://github.com/vuejs/blog/pull/21
