### ISSUE TITLE
GitHub Pages 改用自己的網域 CSS 沒有套用

### ISSUE THREAD

**Issue by snowlinouo** [ATQQ/sugar-blog#280]
這邊尚未使用自訂網域前，使用 Github 的網域查看網站時一切正常

之後我就指定我的自訂網域，開啟網站後網站的 CSS 沒有被套用呈現一片白色
![image](https://github.com/user-attachments/assets/7f8050e2-71a7-44c1-9db0-1a73aff5e417)

Cloudflare DNS 指定設定：
![image](https://github.com/user-attachments/assets/bd3a8f1a-0619-4fba-9924-b61fe0912dab)

網站的 Github Repo：
https://github.com/snowlinouo/snowlin-blog

**Comment by ATQQ** [comment]
自定义域名应该不需要设置base路径，你可以在这里通过环境变量处理一下。

你可以调一下你的.vitepress/config配置文理

**Comment by snowlinouo** [comment]
有了！
謝謝作者QQ

弄了好久一直找不到原因，終於解決惹

![image](https://github.com/user-attachments/assets/cb6bf189-2d4c-4f73-987b-50ebde5bd905)

**Comment by ATQQ** [comment]
👌🏻  perfect
