### ISSUE TITLE
詢問一些小問題

### ISSUE THREAD

**Issue by snowlinouo** [ATQQ/sugar-blog#283]
想詢問一下這部分能可以進行翻譯嗎?
這邊進行翻譯成繁體中文找不太到可以更改文字的設定
![image](https://github.com/user-attachments/assets/9fe82de3-1aca-476a-95d3-243cf5c68fb5)

![image](https://github.com/user-attachments/assets/b5f296bd-94bf-4041-99bd-9af87f5df403)

**Comment by ATQQ** [comment]
OK，目前确实没有提供这部分的定制配置入口。

我加一下，下个小版本带上。

**Comment by ATQQ** [comment]
@sugarat/theme@0.4.10

* https://theme.sugarat.top/config/global.html#article
* https://theme.sugarat.top/config/global.html#formatshowdate
