### ISSUE TITLE
手动指定发布时间后显示NaN-aN-aN

### ISSUE THREAD

**Issue by be154** [ATQQ/sugar-blog#285]
![NaN](https://github.com/user-attachments/assets/030c9065-6312-4237-baae-8ab0217c9616)
只要在frontmatter里加入 `date: 2023-01-08`  就会变成NaN-aN-aN，移除后就正常显示时间
看过其它的issues，我是用的windows系统，文件路径全英文
`docs/posts/announcements/test.md`
并且也没有base路径

**Comment by ATQQ** [comment]
好滴  我下来看一下这个问题 好像是 matter 处理的问题 你可以先写成

2024-01-01 00:00:00

**Comment by be154** [comment]
我改成了这个格式还是会显示NaN-aN-aN
我的变动应该只有：
- 默认首页 `docs/index.md` 改成了其它样式
- 博客首页移动到了 `docs/blog-home/index.md`
尝试过把默认首页改回去不过也没有用

**Comment by ATQQ** [comment]
你看方便给到个能复现的仓库不。我这边在 创建的 demo 项目里 复现不了暂时

**Comment by be154** [comment]
https://github.com/be154/asc-website
大佬可以看一下，代码写的比较拙劣

**Comment by ATQQ** [comment]
<img width="1023" alt="image" src="https://github.com/user-attachments/assets/d2448312-0674-42bd-b828-d13d34450738">

```md
---
date: 2023-01-08
---

# 测试日期
```

<img width="997" alt="image" src="https://github.com/user-attachments/assets/eea475e1-dd29-445e-ba1a-a18687e5b589">


<img width="573" alt="image" src="https://github.com/user-attachments/assets/392bc52c-18ae-40d2-8313-a8322f2b8245">


Mac 上暂时没复现这个问题，我拿 windows 看看。

**Comment by ATQQ** [comment]
我这边 window 上也没能复现这个问题。你那现在还能稳定复现吗

**Comment by be154** [comment]
![image](https://github.com/user-attachments/assets/04f3d20e-cadf-4fa9-8434-8c5ccf0ad14a)
我重新clone了一遍我自己的repo到新的文件夹，之前用npm install，我换成了pnpm install结果还是有这个问题

**Comment by ATQQ** [comment]
那确实诡异，你 Node+pnpm 版本多少

**Comment by be154** [comment]
node v20.14.0
pnpm 8.15.7
是不是有点老我看看更新一下

**Comment by ATQQ** [comment]
把 node_modules 清理了，换 pnpm9 试一下

终端你使用的什么 cmd/powershell/gitbash

**Comment by ATQQ** [comment]
还有 window 是11 还是 10

**Comment by be154** [comment]
win11, powershell,我去试一下

**Comment by ATQQ** [comment]
你可以截图给我看看你终端 
pwd

和 运行的指令后的截图

**Comment by be154** [comment]
更新pnpm9没解决
![image](https://github.com/user-attachments/assets/7946fcae-409c-4846-8293-8f545843881c)

**Comment by ATQQ** [comment]
好滴 我下来 按你的环境再看一下，

你看你电脑上有 git bash 不 把终端换成这个试试（一般随 Git 安装自带的）

**Comment by be154** [comment]
有 我试试

**Comment by be154** [comment]
![image](https://github.com/user-attachments/assets/1e2f6548-df24-4b22-a787-d0c209f7419b)
![image](https://github.com/user-attachments/assets/b2206300-2d97-4253-9eff-7656f8e0edbf)

**Comment by be154** [comment]
![image](https://github.com/user-attachments/assets/dfb4265e-2d7e-471b-bdaf-27d946be7809)
我发现一个诡异的问题

**Comment by ATQQ** [comment]
你按下面步骤操作看一下嘞 看看结果有不有问题

```sh
pnpm add gray-matter
```

```sh
node

require('gray-matter')(`---\ndate: 2021-01-01\n---`)
```

<img width="605" alt="image" src="https://github.com/user-attachments/assets/06dc1c75-161a-4def-b1e0-f62f4277f698">

**Comment by be154** [comment]
![image](https://github.com/user-attachments/assets/3c96d280-11d2-49e1-8e7f-fe6a84224587)
都弄好了以后也不行

**Comment by be154** [comment]
![image](https://github.com/user-attachments/assets/b474e91f-4b10-44e5-91e2-b913908b9691)

**Comment by ATQQ** [comment]
了解了 那我大概知道是哪块的问题了。稍等我再准备个demo

**Comment by be154** [comment]
好，谢谢大佬

**Comment by ATQQ** [comment]
复制下面 这一段进去
```js
const grayMatter = require('gray-matter')

const { data: meta } = grayMatter('---\ndate: 2021-01-01\n---', {
  excerpt: true,
})
console.log('meta', meta)

const defaultTimeZoneOffset = new Date().getTimezoneOffset() / -60
console.log('defaultTimeZoneOffset', defaultTimeZoneOffset)
console.log(new Date(`${new Date(meta.date).toUTCString()}+${defaultTimeZoneOffset}`))
```

<img width="779" alt="image" src="https://github.com/user-attachments/assets/81ae0eff-4aa8-486e-aad1-c00f4f050cea">

**Comment by be154** [comment]
复制好了不过还是没日期

**Comment by ATQQ** [comment]
就是把输出结果我看一下 像我那样截图

**Comment by be154** [comment]
![image](https://github.com/user-attachments/assets/7388e168-7516-4111-bd0f-a6fa94ae8609)
不太会用

**Comment by be154** [comment]
我是不是得一行一行粘

**Comment by be154** [comment]
噢不对我没进node

**Comment by be154** [comment]
![image](https://github.com/user-attachments/assets/d5337609-7da2-4307-94f4-292a6f3edcd1)

**Comment by be154** [comment]
我在国外，时区正好是UTC-7

**Comment by ATQQ** [comment]
这快  我得兼容一下 之前没处理 - 的场景 哈哈
<img width="856" alt="image" src="https://github.com/user-attachments/assets/f14a663a-a9f9-4172-b2ff-a0aa83023806">

**Comment by be154** [comment]
噢噢好的

**Comment by ATQQ** [comment]
你稍等我一小会儿，我快速解决

**Comment by be154** [comment]
好，感谢大佬

**Comment by ATQQ** [comment]
你更新一下 主题包依赖应该就可以了
```sh
pnpm add @sugarat/theme@latest
```

现在最新 `@sugarat/theme@0.4.12`

**Comment by be154** [comment]
解决了，感谢感谢
