### ISSUE TITLE
在开发时使用`--host`参数后主页无法加载文章

### ISSUE THREAD

**Issue by snowykami** [ATQQ/sugar-blog#294]
## 描述

在启动开发服务器时，我想让页面能够在外网访问，便在`vitepress dev`命令后追加了`--host`参数，于是启动后访问主页会出现文章无法加载的情况，情况如下图
![733623f6bdefc78b24cfbdebf7dcaf63](https://github.com/user-attachments/assets/5fa6a133-bf00-467c-853e-94c8e342c67e)

## 预期
移除`--host`参数后恢复正常
![87c731cdec8b8cb72f39c92fa6cf3a84](https://github.com/user-attachments/assets/a78cbbea-85a1-46fb-b47f-a615576dd9f2)

## 其他
猜测可能是</ClientOnly>导致的问题，但是不能完全确定

**Comment by ATQQ** [comment]
OK 我看一下，应该是取 CLI  参数那里有点小问题

可以先配置到 config 配置里
```ts

import { defineConfig } from 'vitepress'

export default defineConfig({
  vite: {
    server: {
      port: 4000,
      host: '0.0.0.0'
    }
  }
})

```

**Comment by ATQQ** [comment]
最新版 @sugarat/theme@0.5.0 解决
