### ISSUE TITLE
默认sidebar偏移

### ISSUE THREAD

**Issue by be154** [ATQQ/sugar-blog#296]
![image](https://github.com/user-attachments/assets/9db073d5-9cf4-4400-94dd-fc5a71f1c3b4)

我在尝试了 #254 后，vitepress默认的sidebar偏移到了左侧，看起来好像和主题的侧边栏有关

![image](https://github.com/user-attachments/assets/dc79105d-ceaa-4396-bf32-623c4628abc9)

请问怎么样才能让默认的sidebar回到正常位置，非常感谢

**Comment by ATQQ** [comment]
这个没 GET 到，你可以来个问题明显的截图 或者复现的 demo 仓库 我看一下

**Comment by be154** [comment]
![image](https://github.com/user-attachments/assets/efb744a5-e3e1-4b9d-8c1f-184be3c78661)
就是默认主题这里的sidebar是和上面那个线对齐的，但是在应用主题后sidebar会向左偏移一点
![image](https://github.com/user-attachments/assets/90bb3227-a75f-4828-9e28-38cf6369ba3a)

**Comment by ATQQ** [comment]
好滴。回头优化一下这里的样式细节。

**Comment by ATQQ** [comment]
最新版 @sugarat/theme@0.5.0 解决
