### ISSUE TITLE
Router Rewrite问题

### ISSUE THREAD

**Issue by be154** [ATQQ/sugar-blog#297]
起因是我在`config.mts`里面添加了这一行
```
rewrites: {
    "posts/example/example.md": "example.md",
  },
```
以及
```
cleanUrls: true
```

一切在本地都能正常跳转，不过在vercel里面就会卡在`posts/example/example`报404，我试了各种vercel.json里面的设置，如redirect，rewrite，routes等但都没办法

我添加了一个测试按钮，`link="/example"`就能正常跳转，但是`link="/posts/example/example"`后我看闪了一下/posts/example/example之后才变成/example，也就导致了我在vercel里看见的404

我想请教一下我该如何让blog主页的这些地方点击后直接跳转/example而不是闪一下/posts/example/example，或者还有没有其他的一些解决办法，感谢大佬
![image](https://github.com/user-attachments/assets/ee671e75-c05b-48f4-bab7-416457064439)

**Comment by ATQQ** [comment]
rewrites的 配置主题这边可能没适配，使用频率比较低，本地没问题应该是 devServer 自己处理了。

回头我看一下这块逻辑适配适配。

**Comment by be154** [comment]
好的，感谢大佬

**Comment by ATQQ** [comment]
最新版 @sugarat/theme@0.5.0 解决
