### ISSUE TITLE
[Bug] 使用CloudFlare Pages部署，文章时间始终为部署时间

### ISSUE THREAD

**Issue by klxiaoniu** [ATQQ/sugar-blog#307]
### 点击创建，选择对应的仓库进行构建

![image](https://github.com/user-attachments/assets/4bbb4f35-ab22-40a5-8322-bd60089b42a9)

### 配置如下，产生新的commit时，CF会自动部署：

![image](https://github.com/user-attachments/assets/c1cefd30-862d-47ef-bb67-b6230945d137)
![image](https://github.com/user-attachments/assets/13d0e89f-957f-4006-b9c7-eb8a5cc600f5)

## Bug现象

除手动指定date的文章，其他文章的更新时间都是最后一次部署的时间，而不是文档中描述的Git Commit时间。
![image](https://github.com/user-attachments/assets/01f4b69f-1aa2-4921-a93a-89509fcced57)

## 问题博客地址

https://github.com/klxiaoniu/klxiaoniu-blog
https://www.klxiaoniu.top/

**Comment by klxiaoniu** [comment]
还有一个小问题，构建时会产生大量的warning如下：

DEPRECATION WARNING: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api

但是我没找到是哪里的使用导致的问题

**Comment by ATQQ** [comment]
自己看一下构建脚本 拉git仓库是否带全量的commit 还是快速拉取没有git信息

**Comment by ATQQ** [comment]
> 还有一个小问题，构建时会产生大量的warning如下：
> 
> DEPRECATION WARNING: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
> 
> More info: https://sass-lang.com/d/legacy-js-api
> 
> 但是我没找到是哪里的使用导致的问题

这个问题今天看一下，看到有其它的反馈，之前看漏了

**Comment by ATQQ** [comment]
sass 的警ttps://sass-lang.com/documentation/breaking-changes/legacy-js-api/

<img width="1009" alt="image" src="https://github.com/user-attachments/assets/812775c7-f5b6-489d-a594-be43678682e3">

https://vite.dev/config/shared-options.html#css-preprocessoroptions

```ts
export default defineConfig({
  vite:{
    css:{
      preprocessorOptions:{
        scss:{
          api: 'modern'
        }
      }
    }
  },
})
```

**Comment by ATQQ** [comment]
下一版 我内置一下这个配置

**Comment by klxiaoniu** [comment]
cloudflare没有公开构建脚本，因此无从查起是否用了全量拉取。

最终折中的解决方案是使用github action进行构建，最后用`cloudflare/wrangler-action@v3`推到cf pages上。修改后的配置：https://github.com/klxiaoniu/klxiaoniu-blog/blob/main/.github/workflows/deploy.yml
