### ISSUE TITLE
如何忽略或解决编译时 legacy JS API 警告

### ISSUE THREAD

**Issue by hacxy** [ATQQ/sugar-blog#310]
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api

**Comment by ATQQ** [comment]
你有自定义样式吗？

之前解决过一个 https://github.com/ATQQ/sugar-blog/issues/270  你看和这是不是一样类似的？

---
我拉demo 看了一下 构建没这个报错，你可以发一下你的仓库 我 look look。

**Comment by hacxy** [comment]
https://github.com/hacxy/blog 
执行`pnpm dev` 编写文档时会出现这个警告
另外打包过程也会出现这个警告
<img width="1024" alt="image" src="https://github.com/user-attachments/assets/68430ea9-ee09-47c2-970f-0ddaecd42b26">

**Comment by ATQQ** [comment]
今天空了看一下这个👌🏻，可能是哪个依赖有升级的问题

**Comment by hacxy** [comment]
不止在一个地方看到过这个警告了, 大概率是sass依赖的版本自动升了, 在vite里面可以这样解决
```ts
  vite: {
    css: {
      preprocessorOptions: {
        scss: {
          api: "modern",
        },
      },
    },
  },
```
参考的这个: https://github.com/sass/dart-sass/issues/2352

**Comment by ATQQ** [comment]
对对对，我也看到文档里有说了，Vite还没替换新的API

 https://sass-lang.com/documentation/breaking-changes/legacy-js-api/

<img width="1009" alt="image" src="https://github.com/user-attachments/assets/812775c7-f5b6-489d-a594-be43678682e3">

https://vite.dev/config/shared-options.html#css-preprocessoroptions

**Comment by ATQQ** [comment]
下一版 我内置一下这个配置
