### ISSUE TITLE
修改字体

### ISSUE THREAD

**Issue by 9uest** [ATQQ/sugar-blog#316]
您好，我想修改下整体的网站字体大小，这个样式应该在哪里改？

body
h1
...

**Comment by ATQQ** [comment]
重载样式就可 在 theme.ts 里引入自定义样式

**Comment by ATQQ** [comment]
<img width="735" alt="image" src="https://github.com/user-attachments/assets/5432366f-408e-482c-a47a-d73dd0cda728">

**Comment by 9uest** [comment]
已经可以了，谢谢了 😊
