### ISSUE TITLE
文章详情的标题无法展示

### ISSUE THREAD

**Issue by mrdear** [ATQQ/sugar-blog#320]
<img width="2181" alt="image" src="https://github.com/user-attachments/assets/f5a73418-cd88-48b7-b4e6-fa06aef7fee3" />

属性配置如下，很奇怪。。
---
title: Building effective agents
description: Anthropic年底针对Agent的总结，很值得一看
tag:
 - LLM
 - Anthropic
 - Agent
recommend: 5
hidden: false
sticky: 1
author: Anthropic
cover: https://resource.libx.fun/pic/2024/12/build_effective_agents.png
date: 2024-12-20
---

**Comment by ATQQ** [comment]
标题得自己用 markdown的 一级标题

```md
# 一级标题
```

**Comment by mrdear** [comment]
thanks，这个和hexo等博客系统还挺不一样的。。。

**Comment by ATQQ** [comment]
这个title 属性主要是用来修改 导航 里的显示的  区别于实际文章内的标题
