### ISSUE TITLE
demo主题运行的时候head属性不加载,页签上不显示小图标

### ISSUE THREAD

**Issue by zq-xu** [ATQQ/sugar-blog#56]

**Comment by ATQQ** [comment]
这边刚试了一下有图标嘞，你是指哪块图标不展示（浏览器tab吗）
![image](https://user-images.githubusercontent.com/42485491/219663983-d2bf6197-55c2-405f-8282-3d14efe7fff4.png)

**Comment by ATQQ** [comment]
head 的配置你可以参考这个

https://github.com/ATQQ/sugar-blog/blob/0b6afff2a995206a2d4603e065a3a8ba88515994/packages/blogpress/.vitepress/config.ts#L90-L108

**Comment by zq-xu** [comment]
> head 的配置你可以参考这个
> 
> https://github.com/ATQQ/sugar-blog/blob/0b6afff2a995206a2d4603e065a3a8ba88515994/packages/blogpress/.vitepress/config.ts#L90-L108

是的 浏览器tab的header里面的link, 已经配置好了，原因应该是favicon.ico的格式原因，替换成了png格式的图片就好了，参考你的theme，我搭建了自己的Blog:https://zq-xu.github.io/
