### ISSUE TITLE
提几个优化的建议

### ISSUE THREAD

**Issue by zq-xu** [ATQQ/sugar-blog#57]
首先得夸一下，这个主题是我这几天在github上找到的基于vitepress的体验最好的主题。

基于这个主题，我构建了自己的博客[ZQ-XU](https://zq-xu.github.io/)，非常感谢owner的分享！

在构建个人博客期间，我也有些许的建议，希望owner在后续的开发中可以考虑一下：
- 多语言的支持，当前貌似是只支持单语种；
- 首页文章和左侧边栏的目录(相关文章)支持自定义/排序，当前貌似是根据当前路径下的文件根据date属性自动排序的(如果没有指定date属性，那么更改了以前的文章，则会打乱原来的顺序)；
- 背景图片的配置，我是参考vitepress的文档，在styles的css文件中覆盖了background-image属性；
- 右侧边栏的标题默认是支持到二级标题的，我是参考了vitepress的文档，根据属性'outline'来配置的，这个可以考虑补充到文档中(对于新人会比较友好)。

祝好~

**Comment by ATQQ** [comment]
感谢如此高的评价

主题是继承官方默认主题的

1,4是官方文档支持 我后续引导一下（可能官方文档目前还没中翻，看得人不多）

2 这一点我考虑一下怎么设计（当前就是按时间，未指定的情况按最后修改时间 通过Git获取 ，这样的好处是 有更新能看到在首页），如果想按照自定排序 准备出个类似置顶的效果

3 的话我优化一下，提供个配置项 😋， 降低一下新手成本，顺便也引导一下使用css定义的方式


----
感谢反馈

**Comment by zq-xu** [comment]
> 感谢如此高的评价
> 
> 主题是继承官方默认主题的
> 
> 1,4是官方文档支持 我后续引导一下（可能官方文档目前还没中翻，看得人不多）
> 
> 2 这一点我考虑一下怎么设计（当前就是按时间，未指定的情况按最后修改时间 通过Git获取 ，这样的好处是 有更新能看到在首页），如果想按照自定排序 准备出个类似置顶的效果
> 
> 3 的话我优化一下，提供个配置项 😋， 降低一下新手成本，顺便也引导一下使用css定义的方式
> 
> 感谢反馈

非常期待~

**Comment by zq-xu** [comment]
> @zq-xu 
> 
> > 首页文章和左侧边栏的目录(相关文章)支持自定义/排序，当前貌似是根据当前路径下的文件根据date属性自动排序的(如果没有指定date属性，那么更改了以前的文章，则会打乱原来的顺序)；
> 
> 
> 
> 这一条上周已经开发完了，可以试试 看看有不有什么反馈

OK  我这两天同步一下试试

**Comment by zq-xu** [comment]
> > @zq-xu 
> > 
> > > 首页文章和左侧边栏的目录(相关文章)支持自定义/排序，当前貌似是根据当前路径下的文件根据date属性自动排序的(如果没有指定date属性，那么更改了以前的文章，则会打乱原来的顺序)；
> > 
> > 
> > 
> > 这一条上周已经开发完了，可以试试 看看有不有什么反馈
> 
> OK  我这两天同步一下试试

Npx指令出来的模板貌似无法指定版本，默认版本还是0.1.0的

**Comment by ATQQ** [comment]
@zq-xu 
模板里是
```sh
 ^0.1.0
```
没有lock文件的时候默认会装0.x最新版

存量项目里直接执行下面的指令即可
```sh
pnpm up @sugarat/theme
```

**Comment by zq-xu** [comment]
> @zq-xu 
> 
> 模板里是
> 
> ```sh
> 
>  ^0.1.0
> 
> ```
> 
> 没有lock文件的时候默认会装0.x最新版
> 
> 
> 
> 存量项目里直接执行下面的指令即可
> 
> ```sh
> 
> pnpm up @sugarat/theme
> 
> ```

我直接在package.json文件中修改了版本号，重新install的。。你说的方法我回来试试。。
