### ISSUE TITLE
发布时间显示为NaN-aN-aN

### ISSUE THREAD

**Issue by miaobuao** [ATQQ/sugar-blog#74]
[https://miaobuao.github.io/posts/%E8%87%AA%E7%84%B6%E8%AF%AD%E8%A8%80%E5%A4%84%E7%90%86.html](https://miaobuao.github.io/posts/%E8%87%AA%E7%84%B6%E8%AF%AD%E8%A8%80%E5%A4%84%E7%90%86.html)

<img width="523" alt="image" src="https://user-images.githubusercontent.com/62047803/227751870-e2dc260f-e36d-4b07-9e4d-65a13fe6a79c.png">

**Comment by ATQQ** [comment]
是什么操作系统嘞 打包的时候😁

我待会儿看一下

**Comment by miaobuao** [comment]
> 是什么操作系统嘞 打包的时候😁
> 
> 我待会儿看一下

用的是github action, 所以不太清楚是什么系统哎

npm run dev的时候也显示NaN, 用的是windows

**Comment by miaobuao** [comment]
这是我的front matter

```
---
date: 2023-03-01 10:35:53
tags: [NLP]
---
```

**Comment by ATQQ** [comment]
问题找到了，中文路径的问题hh

做了下兼容 => https://github.com/ATQQ/sugar-blog/commit/99b13c533160b638c07e78e40f7aaf6fa7541664#diff-b1a88e02d80505eee79589c9d1f2a8b8543d8e3a42ae34d56d82f73bf5fe03b1

待会儿和其它内容一起 发个版嘿嘿

---
时间的话 md 里不指定的话也不影响会通过Git提取文件上次commit的时间信息

**Comment by ATQQ** [comment]
已经解决发版了

```ts
pnpm up @sugarat/theme
```

项目里执行更新一下包版本即可（当前最新 v0.1.16）

**Comment by miaobuao** [comment]
好的谢谢, 辛苦了!
