### ISSUE TITLE
当文章长度不足一个屏幕高度时, 评论按钮会显示错误

### ISSUE THREAD

**Issue by miaobuao** [ATQQ/sugar-blog#76]
很喜欢作者的作品, 确实是我用过最喜欢的VitePress主题! 

在开启评论之后出现了一个问题: [https://miaobuao.github.io/posts/%E5%AE%89%E8%A3%85electron%E5%8D%A1%E4%BD%8F.html](https://miaobuao.github.io/posts/%E5%AE%89%E8%A3%85electron%E5%8D%A1%E4%BD%8F.html)

如图, 当文章比较短的时候, 按照逻辑应该是不显示评论按钮, 但是却居中显示了, 应该是BUG
![image](https://user-images.githubusercontent.com/62047803/227773625-601faf1f-7329-413e-aaf4-7eb346c800e2.png)

当切换到一个较长的文章, 再重新切换回出现问题的短文章时, 评论按钮就被隐藏了.

**Comment by ATQQ** [comment]
哈哈 这个 bug已知 ，我找个时间优化一下 🥲 😄

**Comment by miaobuao** [comment]
好的谢谢作者!!

**Comment by ATQQ** [comment]
问题已修复

升级主题包即可
```sh
pnpm up @sugarat/theme
```
