### ISSUE TITLE
请问本项目能运行吗

### ISSUE THREAD

**Issue by Damiyinliao** [ATQQ/sugar-blog#79]
![image](https://user-images.githubusercontent.com/50024908/229006395-41618372-6836-4018-b6fc-a136da8b93c9.png)
按照提示，pnpm i 之后pnpm dev显示用问题，No projects matched the filters in "E:\GitHub\sugar-blog"

**Comment by ATQQ** [comment]
肯定可以运行嘞

你进入子包操作一下嘞 

```sh
cd packages/blogpress
pnpm install
pnpm dev
```

**Comment by ATQQ** [comment]
你 pnpm 版本是多少呀

**Comment by Damiyinliao** [comment]
> 你 pnpm 版本是多少呀

8.1.0
![image](https://user-images.githubusercontent.com/50024908/229008945-9b6a6f89-0939-4f5c-8386-638ec506fbe2.png)

**Comment by ATQQ** [comment]
要不你先换到  pnpm7

···sh
npm i  -g pnpm@7

再在根目录下运行 pnpm install
···


前几天才发布的 8 可能部分配置还没兼容

**Comment by ATQQ** [comment]
@Damiyinliao 朋友这个问题有解决吗

**Comment by ATQQ** [comment]
![image](https://user-images.githubusercontent.com/42485491/229357046-2bfda186-5922-45bc-92c0-ec7869de0eef.png)

我复现了这个问题，抱歉是我漏了步骤 需要先在 `packages/theme`中进行构建 我这边迭代一下指令

**Comment by ATQQ** [comment]
可以重新拉取一下仓库，新的运行步骤已经更新至README，感谢反馈问题

① 先安装 `pnpm`
```sh
npm i -g pnpm
# 安装依赖
pnpm install
```

② 构建主题包
```sh
pnpm build:theme-only
```

③ 运行
```sh
# 运行博客
pnpm dev

# 运行主题包文档
pnpm dev:theme
```
