### ISSUE TITLE
发布时间都显示为0秒前

### ISSUE THREAD

**Issue by Windstarry** [ATQQ/sugar-blog#80]
md文档的时间已经设置，在发布页里面显示时间都为0秒前
![FireShot Capture 002 - 关于主题 - windstarry's blog - windstarry gitee io](https://user-images.githubusercontent.com/61078000/229017353-c3596fed-1de4-4a6d-922a-8d381608b4c1.png)
这里显示的时间是正确的
![FireShot Capture 003 - windstarry's blog - windstarry's blog - windstarry gitee io](https://user-images.githubusercontent.com/61078000/229017474-e7a0190e-bd6b-422e-88ac-52247bcb1ce3.png)

**Comment by ATQQ** [comment]
什么操作系统呀 win还是mac

是在 dev.启动时间不正确还是 build后 预览的页面时间显示不正确

**Comment by ATQQ** [comment]
咱是不是设置了 base路径😁

**Comment by Windstarry** [comment]
使用的win系统，dev和build预览的时间显示都不正确
因为带有仓库名字，设置了base路径

**Comment by ATQQ** [comment]
了解了，我晚上回去兼容一下 base路径这个，之前漏了这里

**Comment by ATQQ** [comment]
问题已修复

升级主题包即可
```sh
pnpm up @sugarat/theme
```

**Comment by Windstarry** [comment]
> ```shell
> @sugarat/theme
> ```
已经正常显示~
