### ISSUE TITLE
上线后,更新时间显示为8小时前,本地正常显示

### ISSUE THREAD

**Issue by Wzccccc** [ATQQ/sugar-blog#93]
<img width="1639" alt="image" src="https://user-images.githubusercontent.com/87292165/236771044-cf133914-1f56-41b6-a826-1f7f009d1c9e.png">
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/87292165/236771543-96fbe8d8-98d7-4469-9b36-81990c6de749.png">

**Comment by ATQQ** [comment]
图2的时间会按照自己设置的或者默认git记录的文件最后一次修改时间 按照UTC +8 展示的

图1的底部这个最后更细时间是vitepress 默认的 ，应该需要调一下时区它的 印象中有个配置vitepress的

**Comment by ATQQ** [comment]
看你构建是在哪里进行的 本地打包预览你看是否正常

可能构建机器和本地的时区不一样

**Comment by Wzccccc** [comment]
明白了,我是用的是 github actions 时区不一致,我需要在 yml 基本中添加时区,感谢
