### ISSUE TITLE
请教下，样式怎么修改

### ISSUE THREAD

**Issue by wanghuohuoyan** [ATQQ/sugar-blog#94]
左边和右边的宽度有块区域空着
![image](https://user-images.githubusercontent.com/94205527/237028800-aa52b669-09fe-4357-8f63-534b8662223a.png)
我想改下宽度，还有中间区域，宽度也比较窄，我也想改宽些。
java开发，前端开始学🤣，以前用的`docsify`

**Comment by wanghuohuoyan** [comment]
![image](https://user-images.githubusercontent.com/94205527/237031790-20502c8f-cbb2-4ed4-b118-476423a6c192.png)
还想请教下，你这的标签是怎么设置的，GitHub的连接怎么修改

**Comment by ATQQ** [comment]
可以看一下 主题的使用文档哦https://theme.sugarat.top/sop/quickStart.html

**Comment by ATQQ** [comment]
> ![image](https://user-images.githubusercontent.com/94205527/237031790-20502c8f-cbb2-4ed4-b118-476423a6c192.png) 还想请教下，你这的标签是怎么设置的，GitHub的连接怎么修改



> ![image](https://user-images.githubusercontent.com/94205527/237031790-20502c8f-cbb2-4ed4-b118-476423a6c192.png) 还想请教下，你这的标签是怎么设置的，GitHub的连接怎么修改

标签是在每一篇文章里设置的，会自动生成到首页

github地址在.vitepress/config里指定

**Comment by ATQQ** [comment]
样式重载参考这个

https://github.com/ATQQ/sugar-blog/blob/master/packages/template/docs/.vitepress/theme/index.ts

**Comment by ATQQ** [comment]
@wanghuohuoyan 同学的 问题解决了吗 ❓

**Comment by wanghuohuoyan** [comment]
> Owner

解决了，谢谢大佬👍👍👍

**Comment by wanghuohuoyan** [comment]
![Uploading image.png…]()
你这个配置，很强👍👍👍👍👍

**Comment by wanghuohuoyan** [comment]
> @wanghuohuoyan 同学的 问题解决了吗 ❓

大佬，请教下有没有tabs这种功能呀？
![Uploading image.png…]()

**Comment by ATQQ** [comment]
我这看不到你发的图片，看着你没有上传成功

**Comment by wanghuohuoyan** [comment]
> 我这看不到你发的图片，看着你没有上传成功

![image](https://github.com/ATQQ/sugar-blog/assets/94205527/7469aa61-51f5-4ea0-8976-7e0e4bfbb03d)
docsify其中的一个组件
 
<script src="https://cdn.jsdelivr.net/npm/docsify-tabs@1"></script>

**Comment by ATQQ** [comment]
@wanghuohuoyan issue 交流不方便的话 你加我私信也行 😃

**Comment by ATQQ** [comment]
看到图片了，主题没有添加这个功能。我记一下，有时间可以实现 哈哈

**Comment by wanghuohuoyan** [comment]
> 看到图片了，主题没有添加这个功能。我记一下，有时间可以实现 哈哈

强👍👍👍👍👍

**Comment by ATQQ** [comment]
VitePress目前只针对代码提供了一个 [code group ](https://vitepress.dev/guide/markdown#code-groups)

**Comment by ATQQ** [comment]
https://vitepress-plugins.sapphi.red/tabs/

我看社区好像有一个(⊙o⊙)…  你看看能用不

**Comment by wanghuohuoyan** [comment]
> https://vitepress-plugins.sapphi.red/tabs/

我试过报错，然后问了作者，说这些插件只支持ESM🤣

**Comment by ATQQ** [comment]
> > https://vitepress-plugins.sapphi.red/tabs/
> 
> 我试过报错，然后问了作者，说这些插件只支持ESM🤣

fork一下 改改构建产物 😄 加个cjs格式

https://github.com/sapphi-red/vitepress-plugins/blob/7f4c8fe683650f6e8b82addc92c187fe07801fd4/packages/vitepress-plugin-tabs/tsup.config.ts#L1-L7

**Comment by wanghuohuoyan** [comment]
> > > https://vitepress-plugins.sapphi.red/tabs/
> > 
> > 
> > 我试过报错，然后问了作者，说这些插件只支持ESM🤣
> 
> fork一下 改改构建产物 😄 加个cjs格式
> 
> https://github.com/sapphi-red/vitepress-plugins/blob/7f4c8fe683650f6e8b82addc92c187fe07801fd4/packages/vitepress-plugin-tabs/tsup.config.ts#L1-L7

刚刚开始学前端，没搞懂怎么加🤣

**Comment by ATQQ** [comment]
哈哈 那先学习吧

我先建个issue 抽空整一下：https://github.com/ATQQ/sugar-blog/issues/96
