### ISSUE TITLE
tabs支持

### ISSUE THREAD

**Issue by ATQQ** [ATQQ/sugar-blog#96]
> 我这看不到你发的图片，看着你没有上传成功

![image](https://github.com/ATQQ/sugar-blog/assets/94205527/7469aa61-51f5-4ea0-8976-7e0e4bfbb03d)
docsify其中的一个组件
 
<script src="https://cdn.jsdelivr.net/npm/docsify-tabs@1"></script>

_Originally posted by @wanghuohuoyan in https://github.com/ATQQ/sugar-blog/issues/94#issuecomment-1544120629_

**Comment by ATQQ** [comment]
这个已经支持了，详见文档：https://theme.sugarat.top/config/component.html

**Comment by wanghuohuoyan** [comment]
> 这个已经支持了，详见文档：https://theme.sugarat.top/config/component.html

![image](https://github.com/ATQQ/sugar-blog/assets/94205527/788c19dc-a309-4394-b8c5-04dd84dbf715)
这么强吗！！！这就出来了，我就瞅瞅，强呀👍👍👍👍👍👍👍👍👍
